### ISSUE TITLE
multiple samples per species

### ISSUE THREAD

**Issue by k-sanchez** [sungsik-kong/PhyNE.jl#15]
Hi all,
Is it possible to specify multiple samples mapping to each species? This is achievable in the HyDe() function through the `map` argument, but I haven't seen a similar option in the phyne!() function

Thanks!
Kevin

**Comment by sungsik-kong** [comment]
Hi Kevin, phyne!() does not accommodate specifying multiple samples per species yet. It only assumes there is a single lineage per species, but will be accommodated in the future versions. Thanks!
